# Generated by Django 3.2.9 on 2021-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_have_plants',
            field=models.ManyToManyField(blank=True, to='plants.Plant'),
        ),
    ]
