# Generated by Django 3.2.9 on 2021-12-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='review_owner',
        ),
    ]
