# Generated by Django 3.2.9 on 2021-12-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('height_in_cm', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('light_level', models.CharField(default=None, max_length=20)),
                ('watering_frequency', models.CharField(default=None, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
