# Generated by Django 3.2.9 on 2021-12-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20211203_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='price',
            new_name='price_in_GBP',
        ),
    ]
